baseURL = "https://emacstalk.github.io"
languageCode = "zh-cn"
defaultContentLanguage = "cn"
hasCJKLanguage = true
title = "EmacsTalk"
theme = "zen"
copyright = "2021 emacstalk.github.io"
googleAnalytics = "UA-50745138-3"

[author]
    name = "写代码的西瓜"
    email = "jiacai2050+emacstalk@gmail.com"

[[menu.main]]
  name = "播客"
  weight = 20
  identifier = "podcasts"
  url = "/podcast/"
[[menu.main]]
  name = "关于"
  weight = 30
  identifier = "about"
  url = "/about/"
# [[menu.main]]
#   name = "RSS"
#   weight = 40
#   identifier = "rss"
#   url = "/podcast/index.xml"

[params]
    logo = true
    dateformat = "2006-01-02"
    description = "EmacsTalk 是一档专注在 Emacs 社区的程序员闲聊节目。干货不能不要，湿货不能没有。M-x thanks-for-listening"
    feedlinks = false
    realfavicongenerator = true
    relatedposts = true
    submitted = true
    sidebar = true
    mobileMenu = true
    copyright = "© 2021 [EmacsTalk](https://github.com/EmacsTalk/emacstalk.github.io) Licensed under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)"
    footer = "Powered by [Hugo](https://gohugo.io/) and the [Zen theme](https://github.com/frjo/hugo-theme-zen)."
    [params.podcast]
        local = false
        image = "itunes_3000.jpg"
        lang = "zh-cn"
        author = "emacstalk.github.io"
        [params.podcast.category]
            name = "Technology"
        [params.podcast.owner]
            name = "写代码的西瓜"
            email = "jiacai2050@gmail.com"
