baseURL = "https://emacstalk.github.io"
languageCode = "zh-cn"
defaultContentLanguage = "cn"
hasCJKLanguage = true
title = "EmacsTalk"
theme = "zen"
copyright = "2021 emacstalk.github.io"
googleAnalytics = "UA-50745138-3"

[author]
    name = "å†™ä»£ç çš„è¥¿ç“œ"
    email = "emacstalk@liujiacai.net"

[[menu.main]]
  name = "æ’­å®¢"
  weight = 20
  identifier = "podcasts"
  url = "/podcast/"
[[menu.main]]
  name = "å…³äº"
  weight = 30
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "å‚ä¸å½•åˆ¶"
  weight = 40
  identifier = "joinus"
  url = "https://github.com/EmacsTalk/joinus"
[[menu.main]]
  name = "ğŸ”¥ çˆ±å‘ç”µ ğŸ”¥"
  weight = 50
  identifier = "afdian"
  url = "https://afdian.net/@emacstalk"
# [[menu.main]]
#   name = "RSS"
#   weight = 40
#   identifier = "rss"
#   url = "/podcast/index.xml"

[params]
    logo = true
    contactus = """
-   QQ å¬å‹ç¾¤ï¼š[530146104](https://jq.qq.com/?_wv=1027&k=9tAXJ8gG)
-   TG å¬å‹ç¾¤ï¼š<https://t.me/emacstalk>
-   æ”¶å¬æ–¹å¼è§ï¼š<https://emacstalk.github.io/>
-   å¦‚æœæ‚¨å–œæ¬¢è¿™æ¡£èŠ‚ç›®ï¼Œæ¬¢è¿é€šè¿‡[ã€Œâ¤ï¸å‘ç”µã€](https://afdian.net/@emacstalk)æ¥æ”¯æŒ
"""
    dateformat = "2006-01-02"
    description = "EmacsTalk æ˜¯ä¸€æ¡£ä¸“æ³¨åœ¨ Emacs ç¤¾åŒºçš„ç¨‹åºå‘˜é—²èŠèŠ‚ç›®ã€‚å®˜ç½‘ï¼šemacstalk.github.ioã€‚M-x thanks-for-listening"
    feedlinks = false
    realfavicongenerator = true
    relatedposts = true
    submitted = true
    sidebar = true
    mobileMenu = true
    copyright = "Â© 2021 [EmacsTalk](https://github.com/EmacsTalk/emacstalk.github.io) Licensed under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)"
    poweredby = true
    # footer = "footer"
    [params.podcast]
        local = false
        image = "itunes_3000.jpg"
        lang = "zh-cn"
        author = "emacstalk.github.io"
        [params.podcast.category]
            name = "Technology"
        [params.podcast.owner]
            name = "å†™ä»£ç çš„è¥¿ç“œ"
            email = "jiacai2050@gmail.com"
