baseURL = "https://emacstalk.github.io"
languageCode = "zh-cn"
defaultContentLanguage = "en"
hasCJKLanguage = true
title = "EmacsTalk"
theme = "zen"
copyright = "2021 emacstalk.github.io"
googleAnalytics = "UA-50745138-3"
paginate = 10
paginatePath = "page"
enableGitInfo = true

[frontmatter]
  lastmod = [':git', 'lastmod', ':fileModTime', ':default']

[author]
    name = "å†™ä»£ç çš„è¥¿ç“œ"
    email = "emacstalk@liujiacai.net"

[[menu.main]]
  name = "æ’­å®¢"
  weight = 20
  identifier = "podcast"
  url = "/podcast/"
[[menu.main]]
  name = "æ–‡ç« "
  weight = 21
  identifier = "post"
  url = "/post/"
[[menu.main]]
  name = "å…³äº"
  weight = 30
  identifier = "about"
  url = "/about/"
[[menu.main]]
  name = "ğŸ”¥ çˆ±å‘ç”µ ğŸ”¥"
  weight = 50
  identifier = "afdian"
  url = "/donate"

[params]
    logo = true
    mainSections = ["post", "podcast"]
    fadian = """
#### å…¬å‘Šæ  -- Bulletin Board
1. æ‹›å‹Ÿ [Podcast å˜‰å®¾](https://github.com/emacstalk/joinus)ï¼Œåˆ†äº«æ‚¨ä¸ Emacs çš„æ•…äº‹
2. æ¬¢è¿[æŠ•ç¨¿](https://github.com/EmacsTalk/emacstalk.github.io/issues/new)ï¼Œä¸å¤§å®¶ä¸€èµ·åˆ†äº« Emacs ä½¿ç”¨æŠ€å·§
3. å¦‚æœ EmacsTalk å¯¹æ‚¨æœ‰æ‰€å¸®åŠ©ï¼Œæ¬¢è¿è¿›è¡Œ[å‘ç”µæ”¯æŒ](https://mp.weixin.qq.com/s/zWyW5t46KuSEl6usoCifsw) â¤ï¸
"""
    contactus = """
-   å¾®ä¿¡æœç´¢å…¬ä¼—å·[ã€ŒEmacsTalkã€](/images/weixin.jpg)
-   QQ å¬å‹ç¾¤ï¼š[530146104](https://jq.qq.com/?_wv=1027&k=9tAXJ8gG)
-   TG å¬å‹ç¾¤ï¼š<https://t.me/emacstalk>
-   æ”¶å¬æ–¹å¼è§ï¼š<https://emacstalk.github.io/>
-   å¦‚æœæ‚¨å–œæ¬¢è¿™æ¡£èŠ‚ç›®ï¼Œæ¬¢è¿é€šè¿‡[ã€Œâ¤ï¸å‘ç”µã€](https://afdian.net/@emacstalk)æ¥æ”¯æŒ
"""
    dateformat = "2006-01-02"
    description = "EmacsTalk æ˜¯ä¸€æ¡£ä¸“æ³¨åœ¨ Emacs ç¤¾åŒºçš„ç¨‹åºå‘˜é—²èŠèŠ‚ç›®ã€‚å®˜ç½‘ï¼šemacstalk.github.ioã€‚M-x thanks-for-listening"
    feedlinks = false
    realfavicongenerator = true
    relatedposts = true
    submitted = true
    sidebar = true
    mobileMenu = true
    copyright = "Â© 2021 [EmacsTalk](https://github.com/EmacsTalk/emacstalk.github.io) Licensed under [CC BY-NC-ND 4.0](https://creativecommons.org/licenses/by-nc-nd/4.0/)"
    poweredby = true
    # footer = "footer"
    [params.podcast]
        local = false
        image = "logo3000.png"
        lang = "zh-cn"
        author = "emacstalk.github.io"
        [params.podcast.category]
            name = "Technology"
        [params.podcast.owner]
            name = "å†™ä»£ç çš„è¥¿ç“œ"
            email = "jiacai2050@gmail.com"
